version: "3"
services:
  vote:
    build: ./vote
    ports:
      - "8080:80"
    depends_on:
      - redis

  redis:
    image: redis
  db:
    image: postgres:9.4
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
  worker:
    build: ./worker
    depends_on:
      - redis
      - db
  result:
    build: ./result
    ports:
      - "5001:80"
    depends_on:
      - redis
      - db
